name: "Dotnet Test With Auto Retry"
description: "Runs dotnet test and retries failed tests once if there are less than 10 failed tests"
inputs:
  tests_filter:
    description: "Argument to pass to --filter"
    required: true
  test_results_file_name_prefix:
    description: "File name prefix to save results to. Should be in the form prefix-attempt-runattempt e.g. MyTestResults-attempt-2"
    required: true
  test_results_artifact_name:
    description: "The name of the artifact to create for the test results"
    required: true
runs:
  using: "composite"
  steps:
    - name: Test SampleTests
      shell: bash
      run: |
        dotnet test ./SampleTests/SampleTests.csproj --configuration Release --no-restore --no-build --filter "${{inputs.tests_filter}}" --verbosity normal '-l:trx;LogFileName=${{inputs.test_results_file_name_prefix}}.xml' --RunConfiguration.TreatNoTestsAsError=true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.test_results_artifact_name}} # Eventually get TestSampleTests as input. The action uses this name to search for the test results on rerun
        path: ./SampleTests/TestResults/${{inputs.test_results_file_name_prefix}}.xml # Eventually get TestSampleTests as input